version: '3.4'
services:
  vue:
    container_name: vue
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    volumes:
      - .:/app:cached
#      - .:/app/node_modules:delegated
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
    ports:
      - '80:80'
    environment:
      - NODE_ENV=development
    tty: true
